#!/usr/bin/python3 -I
"""Map one validated per-task Codex managed MCP block into container policy."""

import hashlib
import json
import math
import os
from pathlib import Path
import re
import stat
import uuid


D2_SOURCE_SHA256 = "30f0d4363e4ddafca0d2cb8a49e4807d7ee56da8374a9025add70cf1147dc2d8"
D2_BUILD_SHA256 = "4316863681f5378a5846cdb48ff49ccb49daeff353f5cdbeeab0740f0e4e8bbc"
D2_BINARY_SHA256 = "0e3f16bb910154660d5bc8c22b4e3de16f0a20504d8b79487a70c589f28eb5e3"

BEGIN_MARKER = "# BEGIN multica-managed mcp_servers (do not edit; regenerated by daemon)"
END_MARKER = "# END multica-managed mcp_servers"
SCHEMA = "ALTERA_CODEX_MCP_MAP_V1"
MAX_CONFIG_BYTES = 65536
MAX_STRING_BYTES = 16384
MAX_DEPTH = 16
MAX_CATALOG_BYTES = 8192

_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")
_NUMBER = re.compile(r"-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?")
_POLICY_VERSION = re.compile(r"[A-Za-z0-9._-]{1,128}")
_TRACE_COMMANDS = {
    "/Users/egorbondarenko/.trace/bin/trace",
    "/Users/egorbondarenko/.trace/bin/trace-mcp",
}
_PLAYWRIGHT_ARGS = {
    ("-y", "@playwright/mcp"),
    ("-y", "@playwright/mcp@latest"),
    ("-y", "@playwright/mcp", "--headless"),
    ("-y", "@playwright/mcp@latest", "--headless"),
}
_SECRET_PARTS = ("auth", "cookie", "credential", "env", "header", "password", "secret", "token")


PLAYWRIGHT_VECTOR = [
    "/usr/bin/env", "-i", "PATH=/usr/local/bin:/usr/bin:/bin",
    "HOME=/runtime/cache/playwright-home", "TMPDIR=/runtime/tmp",
    "PLAYWRIGHT_BROWSERS_PATH=/ms-playwright", "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1",
    "PLAYWRIGHT_SKIP_BROWSER_GC=1", "npm_config_offline=true", "/usr/local/bin/node",
    "/opt/playwright-mcp/node_modules/@playwright/mcp/cli.js", "--headless", "--sandbox",
    "--executable-path=/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux-arm64/chrome-headless-shell",
    "--isolated", "--block-service-workers", "--allowed-origins=http://altera-web:3000",
    "--codegen=none", "--image-responses=omit", "--output-dir=/runtime/evidence/playwright",
    "--output-max-size=16777216",
]
PLAYWRIGHT_SECCOMP = "e75c64002d22c7893bbc3aef2f8d7c0dde8f673254d0846d9182e89b180024f1"
PLAYWRIGHT_SOURCES = ("Dockerfile", "playwright-mcp/package.json", "playwright-mcp/package-lock.json",
                      "playwright-seccomp.json", "codex_toml_map.py", "runtime.py", "playwright-mcp-canary.mjs")
PLAYWRIGHT_ARTIFACTS = ("browser", "env_executable", "browsers_json", "packages_tree", "browsers_tree")
PLAYWRIGHT_CHECKS = ("static", "tools", "screenshot", "readonly", "no_download", "network",
                     "sandbox", "environment", "stdio_signal", "cleanup")


def playwright_receipt_template(image):
    """Каркас без результатов: сам по себе не разрешает mapping."""
    root = Path(__file__).resolve().parent
    return {"schema": "ALTERA_PLAYWRIGHT_STATIC_V1", "image": image,
            "platform": "linux/arm64", "os": "debian12", "node": "24.12.0",
            "mcp": "0.0.80", "core": "1.63.0-alpha-2026-08-31",
            "browser_revision": "1243", "browser_version": "153.0.8010.12",
            "vector_sha256": _digest(_canonical_json(PLAYWRIGHT_VECTOR)),
            "sources": {name: _digest((root / name).read_bytes()) for name in PLAYWRIGHT_SOURCES},
            "artifacts": {}, "checks": {}}


def read_playwright_attestation(reference):
    """Только coordinator receipt с внешним digest; никаких caller readiness booleans."""
    try:
        if not isinstance(reference, dict) or set(reference) != {"path", "sha256", "image"}:
            _fail("playwright_attestation_invalid")
        path = Path(reference["path"])
        if (not path.is_absolute() or str(path.resolve(strict=True)) != str(path) or
                not re.fullmatch(r"[a-f0-9]{64}", reference["sha256"]) or
                not re.fullmatch(r"sha256:[a-f0-9]{64}", reference["image"])):
            _fail("playwright_attestation_invalid")
        parent = path.parent.lstat()
        before = path.lstat()
        if (not stat.S_ISDIR(parent.st_mode) or stat.S_IMODE(parent.st_mode) != 0o700 or
                parent.st_uid != os.getuid() or not stat.S_ISREG(before.st_mode) or
                stat.S_IMODE(before.st_mode) != 0o600 or before.st_uid != os.getuid() or
                before.st_nlink != 1 or not 0 < before.st_size <= MAX_CATALOG_BYTES):
            _fail("playwright_attestation_invalid")
        fd = os.open(str(path), os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK)
        try:
            if _identity(os.fstat(fd)) != _identity(before):
                _fail("playwright_attestation_invalid")
            data = _read_all(fd)
            if (_identity(os.fstat(fd)) != _identity(before) or _identity(path.lstat()) != _identity(before) or
                    _identity(path.parent.lstat()) != _identity(parent)):
                _fail("playwright_attestation_invalid")
        finally:
            os.close(fd)
        if _digest(data) != reference["sha256"]:
            _fail("playwright_attestation_invalid")
        record = json.loads(data)
        expected = playwright_receipt_template(reference["image"])
        if (not isinstance(record, dict) or set(record) != set(expected) or _canonical_json(record) != data or
                any(record[key] != value for key, value in expected.items() if key not in ("artifacts", "checks"))):
            _fail("playwright_attestation_invalid")
        for key, names in (("artifacts", PLAYWRIGHT_ARTIFACTS), ("checks", PLAYWRIGHT_CHECKS)):
            if (not isinstance(record[key], dict) or set(record[key]) != set(names) or
                    any(not isinstance(v, str) or not re.fullmatch(r"[a-f0-9]{64}", v) for v in record[key].values())):
                _fail("playwright_attestation_invalid")
        return record
    except (OSError, TypeError, ValueError, KeyError):
        _fail("playwright_attestation_invalid")


class MappingError(ValueError):
    """A fixed, non-disclosing mapper failure."""

    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _fail(code):
    raise MappingError(code) from None


def _digest(data):
    return hashlib.sha256(data).hexdigest()


def _canonical_json(value):
    encoded = (json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n").encode()
    if len(encoded) > MAX_CATALOG_BYTES:
        _fail("input_bound_exceeded")
    return encoded


def _decode_config(data):
    if not isinstance(data, bytes) or len(data) > MAX_CONFIG_BYTES:
        _fail("input_bound_exceeded")
    if data.startswith(b"\xef\xbb\xbf") or b"\x00" in data or b"\r" in data:
        _fail("config_encoding_invalid")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        _fail("config_encoding_invalid")
    if (any(ord(character) < 32 and character not in "\t\n" for character in text) or
            any(character in "\u0085\u2028\u2029" for character in text)):
        _fail("config_encoding_invalid")
    return text


def _lexical_markers(text, *, multiline_prefix=False):
    if '\"\"\"' in text or "'''" in text:
        _fail("managed_block_ambiguous")

    recognized = []
    lines = text.splitlines()
    square = 0
    curly = 0
    for line_number, line in enumerate(lines):
        if line in (BEGIN_MARKER, END_MARKER):
            if square or curly:
                _fail("managed_block_ambiguous")
            recognized.append((line_number, line))
            continue
        state = "normal"
        escaped = False
        for character in line:
            if state == "comment":
                break
            if state == "basic":
                if escaped:
                    escaped = False
                elif character == "\\":
                    escaped = True
                elif character == '"':
                    state = "normal"
                continue
            if state == "literal":
                if character == "'":
                    state = "normal"
                continue
            if character == "#":
                state = "comment"
            elif character == '"':
                state = "basic"
            elif character == "'":
                state = "literal"
            elif character == "[":
                square += 1
            elif character == "]":
                square -= 1
            elif character == "{":
                curly += 1
            elif character == "}":
                curly -= 1
            if square < 0 or curly < 0:
                _fail("managed_block_ambiguous")
        if (state in ("basic", "literal") or escaped or curly or
                (square and (not multiline_prefix or recognized))):
            _fail("managed_block_ambiguous")

    if square or curly:
        _fail("managed_block_ambiguous")

    raw_begin = text.count(BEGIN_MARKER)
    raw_end = text.count(END_MARKER)
    if not recognized and raw_begin == 0 and raw_end == 0:
        return None
    if raw_begin != 1 or raw_end != 1 or len(recognized) != 2:
        _fail("managed_block_invalid")
    if recognized[0][1] != BEGIN_MARKER or recognized[1][1] != END_MARKER:
        _fail("managed_block_invalid")
    begin_index, end_index = recognized[0][0], recognized[1][0]
    if begin_index >= end_index:
        _fail("managed_block_invalid")
    nonblank = [index for index, line in enumerate(lines) if line.strip()]
    if not text.endswith("\n") or not nonblank or nonblank[-1] != end_index:
        _fail("managed_block_invalid")
    return lines[begin_index + 1:end_index]


class _ValueParser:
    def __init__(self, value):
        self.value = value
        self.position = 0

    def parse(self):
        result = self._value(1)
        self._spaces()
        if self.position != len(self.value):
            _fail("managed_value_invalid")
        return result

    def _spaces(self):
        while self.position < len(self.value) and self.value[self.position] in " \t":
            self.position += 1

    def _value(self, depth):
        if depth > MAX_DEPTH:
            _fail("input_bound_exceeded")
        self._spaces()
        if self.position >= len(self.value):
            _fail("managed_value_invalid")
        current = self.value[self.position]
        if current == '"':
            return self._string()
        if current == "[":
            return self._array(depth)
        if current == "{":
            return self._inline_table(depth)
        for literal, result in (("true", True), ("false", False)):
            if self.value.startswith(literal, self.position):
                self.position += len(literal)
                return result
        match = _NUMBER.match(self.value, self.position)
        if not match:
            _fail("managed_value_invalid")
        token = match.group(0)
        self.position = match.end()
        try:
            if "." in token or "e" in token.lower():
                number = float(token)
                if not math.isfinite(number):
                    _fail("managed_value_invalid")
                return number
            return int(token)
        except (OverflowError, ValueError):
            _fail("managed_value_invalid")

    def _string(self):
        self.position += 1
        pieces = []
        escapes = {"b": "\b", "t": "\t", "n": "\n", "f": "\f", "r": "\r", '"': '"', "\\": "\\"}
        while self.position < len(self.value):
            character = self.value[self.position]
            self.position += 1
            if character == '"':
                decoded = "".join(pieces)
                try:
                    size = len(decoded.encode("utf-8"))
                except UnicodeEncodeError:
                    _fail("managed_value_invalid")
                if size > MAX_STRING_BYTES:
                    _fail("input_bound_exceeded")
                return decoded
            if character == "\\":
                if self.position >= len(self.value):
                    _fail("managed_value_invalid")
                escape = self.value[self.position]
                self.position += 1
                if escape in escapes:
                    pieces.append(escapes[escape])
                    continue
                if escape in ("u", "U"):
                    width = 4 if escape == "u" else 8
                    raw = self.value[self.position:self.position + width]
                    if len(raw) != width or not re.fullmatch(r"[0-9A-Fa-f]+", raw):
                        _fail("managed_value_invalid")
                    self.position += width
                    try:
                        character = chr(int(raw, 16))
                        character.encode("utf-8")
                    except (ValueError, UnicodeEncodeError):
                        _fail("managed_value_invalid")
                    pieces.append(character)
                    continue
                _fail("managed_value_invalid")
            elif ord(character) < 32:
                _fail("managed_value_invalid")
            else:
                pieces.append(character)
        _fail("managed_value_invalid")

    def _array(self, depth):
        self.position += 1
        result = []
        self._spaces()
        if self.position < len(self.value) and self.value[self.position] == "]":
            self.position += 1
            return result
        while True:
            result.append(self._value(depth + 1))
            self._spaces()
            if self.position >= len(self.value):
                _fail("managed_value_invalid")
            if self.value[self.position] == "]":
                self.position += 1
                return result
            if self.value[self.position] != ",":
                _fail("managed_value_invalid")
            self.position += 1
            self._spaces()
            if self.position >= len(self.value) or self.value[self.position] == "]":
                _fail("managed_value_invalid")

    def _inline_table(self, depth):
        self.position += 1
        result = {}
        self._spaces()
        if self.position < len(self.value) and self.value[self.position] == "}":
            self.position += 1
            return result
        while True:
            match = _BARE_KEY.match(self.value, self.position)
            if not match:
                _fail("managed_value_invalid")
            key = match.group(0)
            self.position = match.end()
            if not self.value.startswith(" = ", self.position) or key in result:
                _fail("managed_value_invalid")
            self.position += 3
            result[key] = self._value(depth + 1)
            self._spaces()
            if self.position >= len(self.value):
                _fail("managed_value_invalid")
            if self.value[self.position] == "}":
                self.position += 1
                return result
            if self.value[self.position] != ",":
                _fail("managed_value_invalid")
            self.position += 1
            self._spaces()
            if self.position >= len(self.value) or self.value[self.position] == "}":
                _fail("managed_value_invalid")


def _parse_managed(data, *, selected_policy=False):
    text = _decode_config(data)
    lines = _lexical_markers(text, multiline_prefix=selected_policy)
    if lines is None:
        return None
    tables = {}
    current = None
    for line in lines:
        if not line:
            continue
        table = re.fullmatch(r"\[mcp_servers\.([A-Za-z0-9_-]+)\]", line)
        if table:
            current = table.group(1)
            if current in tables or len(tables) >= (32 if selected_policy else 3):
                _fail("managed_block_invalid")
            tables[current] = {}
            continue
        assignment = re.fullmatch(r"([A-Za-z0-9_-]+) = (.+)", line)
        if not assignment or current is None:
            _fail("managed_value_invalid")
        key, raw_value = assignment.groups()
        if key in tables[current]:
            _fail("managed_value_invalid")
        tables[current][key] = _ValueParser(raw_value).parse()
    return tables


def _server_rows():
    return [
        {"name": "context7", "present": False, "shape": "absent", "mapping_ready": False},
        {"name": "playwright", "present": False, "shape": "absent", "mapping_ready": False},
        {"name": "trace", "present": False, "shape": "absent", "mapping_ready": False},
    ]


def _secret_key(key):
    lowered = key.lower()
    return any(part in lowered for part in _SECRET_PARTS)


def _render_block(ready):
    lines = [BEGIN_MARKER]
    first = True
    for name in ("context7", "playwright", "trace"):
        if name not in ready:
            continue
        if not first:
            lines.append("")
        first = False
        lines.append("[mcp_servers.%s]" % name)
        if name == "context7":
            lines.extend(("experimental_use_rmcp_client = true", 'url = "https://mcp.context7.com/mcp"'))
        elif name == "playwright":
            lines.extend(('command = "/usr/bin/env"', 'args = ' + json.dumps(PLAYWRIGHT_VECTOR[1:], separators=(",", ":"))))
        else:
            lines.extend(('command = "/usr/local/bin/trace-mcp"', 'args = ["serve"]'))
    lines.append(END_MARKER)
    return ("\n".join(lines) + "\n").encode()


def build_mapping(data, mapping_policy_version, required_servers=(), *, playwright=None):
    """Разобрать managed TOML; optional receipt читается только через строгий validator."""
    if not isinstance(mapping_policy_version, str) or not _POLICY_VERSION.fullmatch(mapping_policy_version):
        _fail("mapping_policy_invalid")
    if (not isinstance(required_servers, (tuple, list)) or
            any(not isinstance(name, str) or name not in ("context7", "playwright", "trace")
                for name in required_servers) or
            len(required_servers) != len(set(required_servers))):
        _fail("required_roster_invalid")

    selected_policy = mapping_policy_version == "codex-mcp-map-selected-v2"
    if selected_policy and not required_servers:
        _fail("required_roster_invalid")
    attestation = read_playwright_attestation(playwright) if playwright is not None else None
    tables = _parse_managed(data, selected_policy=selected_policy)
    rows = _server_rows()
    catalog = {
        "schema": SCHEMA,
        "managed_state": "unresolved" if tables is None else ("explicit_empty" if not tables else "explicit_nonempty"),
        "descriptor_valid": True,
        "unknown_servers_present": False,
        "unknown_fields_present": False,
        "secret_fields_present": False,
        "servers": rows,
        "managed_mapping_verified": False,
    }
    failure = None
    if selected_policy:
        catalog.update(selection=sorted(required_servers), excluded_server_count=0)
    path_map = {}
    ready = set()
    if tables is None:
        failure = "managed_config_absent"
    else:
        by_name = {row["name"]: row for row in rows}
        for name, fields in tables.items():
            if selected_policy and name not in required_servers:
                catalog["excluded_server_count"] += 1
                continue
            if name not in by_name:
                catalog["unknown_servers_present"] = True
                catalog["unknown_fields_present"] = bool(fields) or catalog["unknown_fields_present"]
                catalog["secret_fields_present"] = (catalog["secret_fields_present"] or
                                                     any(_secret_key(key) for key in fields))
                failure = "unverified_managed_config"
                continue
            row = by_name[name]
            row["present"] = True
            unknown = False
            if name == "context7":
                expected = {"experimental_use_rmcp_client", "url"}
                valid = (set(fields) == expected and fields.get("experimental_use_rmcp_client") is True and
                         fields.get("url") == "https://mcp.context7.com/mcp")
                shape = "context7_public_mcp"
            elif name == "trace":
                expected = {"command", "args"}
                command = fields.get("command")
                arguments = fields.get("args")
                valid = (set(fields) == expected and isinstance(command, str) and
                         command in _TRACE_COMMANDS and isinstance(arguments, list) and
                         all(isinstance(argument, str) for argument in arguments) and
                         arguments == ["serve"])
                shape = "trace_serve"
            else:
                expected = {"command", "args"}
                command = fields.get("command")
                arguments = fields.get("args")
                valid = (set(fields) == expected and isinstance(command, str) and command == "npx" and
                         isinstance(arguments, list) and
                         all(isinstance(argument, str) for argument in arguments) and
                         tuple(arguments) in _PLAYWRIGHT_ARGS)
                shape = "playwright_dynamic_npx"
            if set(fields) - expected:
                unknown = True
                catalog["unknown_fields_present"] = True
                catalog["secret_fields_present"] = (catalog["secret_fields_present"] or
                                                     any(_secret_key(key) for key in set(fields) - expected))
            if valid and name != "playwright":
                row.update(shape=shape, mapping_ready=True)
                ready.add(name)
                if name == "trace":
                    path_map[fields["command"]] = "/usr/local/bin/trace-mcp"
            elif valid and attestation is not None:
                row.update(shape="playwright_static_0_0_80", mapping_ready=True)
                ready.add(name)
            elif valid:
                row.update(shape=shape, mapping_ready=False)
                failure = failure or "mapping_not_ready"
            else:
                row.update(shape="unverified", mapping_ready=False)
                failure = "unverified_managed_config"
                if unknown:
                    catalog["unknown_fields_present"] = True

        if failure is None:
            if any(not by_name[name]["present"] or not by_name[name]["mapping_ready"] for name in required_servers):
                failure = "required_server_missing"
            else:
                catalog["managed_mapping_verified"] = True

    catalog_json = _canonical_json(catalog)
    block = _render_block(ready) if failure is None else None
    return {
        "catalog": catalog,
        "catalog_json": catalog_json,
        "catalog_sha256": _digest(catalog_json),
        "mapping_digest": _digest(catalog_json + b"\x00" + mapping_policy_version.encode()),
        "path_map": path_map,
        "policy_block": block,
        "failure": failure,
    }


def _identity(info):
    return (info.st_dev, info.st_ino, stat.S_IFMT(info.st_mode), stat.S_IMODE(info.st_mode),
            info.st_uid, info.st_gid, info.st_nlink, info.st_size, info.st_mtime_ns, info.st_ctime_ns)


def _inode_identity(info):
    return (info.st_dev, info.st_ino, stat.S_IFMT(info.st_mode), stat.S_IMODE(info.st_mode),
            info.st_uid, info.st_gid, info.st_size)


def _read_all(fd):
    chunks = []
    total = 0
    while True:
        try:
            chunk = os.read(fd, min(8192, MAX_CONFIG_BYTES + 1 - total))
        except BlockingIOError:
            _fail("config_metadata_invalid")
        if not chunk:
            break
        chunks.append(chunk)
        total += len(chunk)
        if total > MAX_CONFIG_BYTES:
            _fail("input_bound_exceeded")
    return b"".join(chunks)


def _validate_descriptor(record, workspace_root, expected_cwd, expected_uid):
    if not isinstance(expected_uid, int) or isinstance(expected_uid, bool) or expected_uid < 0:
        _fail("descriptor_invalid")
    if not isinstance(record, dict) or record.get("binary_sha256") != D2_BINARY_SHA256:
        _fail("descriptor_invalid")
    descriptor = record.get("descriptor")
    if not isinstance(descriptor, dict):
        _fail("descriptor_invalid")
    expected = {
        "source_sha256": D2_SOURCE_SHA256,
        "build_sha256": D2_BUILD_SHA256,
        "read_status": "lexical_candidate",
        "canonical_identity": "not_checked",
        "task_acceptance": "not_checked",
        "cwd_matches_expected": True,
    }
    if any(descriptor.get(key) != value for key, value in expected.items()):
        _fail("descriptor_invalid")
    if not isinstance(descriptor.get("argc"), int) or isinstance(descriptor.get("argc"), bool):
        _fail("descriptor_invalid")
    for value in (workspace_root, expected_cwd):
        if not isinstance(value, str) or not value.startswith("/") or os.path.normpath(value) != value:
            _fail("descriptor_invalid")
    if os.getcwd() != expected_cwd:
        _fail("descriptor_invalid")
    candidate = descriptor.get("candidate_path")
    try:
        candidate_size = len(candidate.encode("utf-8")) if isinstance(candidate, str) else None
    except UnicodeEncodeError:
        _fail("descriptor_invalid")
    if candidate_size is None or candidate_size > 1024:
        _fail("descriptor_invalid")
    pattern = re.escape(workspace_root) + r"/alte-[0-9]{1,9}-[0-9a-f]{12}/codex-home"
    if not re.fullmatch(pattern, candidate):
        _fail("descriptor_invalid")
    return candidate


def _read_validated_config(candidate, workspace_root, expected_uid):
    components = candidate[1:].split("/")
    workspace_components = workspace_root[1:].split("/")
    if components[:len(workspace_components)] != workspace_components:
        _fail("descriptor_invalid")
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW
    file_flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK
    fds = []
    initial = []
    try:
        try:
            fds.append(os.open("/", directory_flags))
            initial.append(os.fstat(fds[-1]))
            for index, component in enumerate(components):
                fd = os.open(component, directory_flags, dir_fd=fds[-1])
                info = os.fstat(fd)
                if not stat.S_ISDIR(info.st_mode):
                    os.close(fd)
                    _fail("descriptor_invalid")
                if index + 1 >= len(workspace_components):
                    if info.st_uid != expected_uid or stat.S_IMODE(info.st_mode) & 0o022:
                        os.close(fd)
                        _fail("descriptor_invalid")
                fds.append(fd)
                initial.append(info)
        except (OSError, ValueError):
            _fail("descriptor_invalid")

        try:
            config_fd = os.open("config.toml", file_flags, dir_fd=fds[-1])
        except OSError:
            _fail("config_metadata_invalid")
        try:
            before = os.fstat(config_fd)
            if (not stat.S_ISREG(before.st_mode) or before.st_uid != expected_uid or
                    stat.S_IMODE(before.st_mode) != 0o600 or before.st_nlink != 1 or
                    before.st_size > MAX_CONFIG_BYTES):
                _fail("config_metadata_invalid")
            data = _read_all(config_fd)
            after = os.fstat(config_fd)
            if _identity(after) != _identity(before) or len(data) != before.st_size:
                _fail("descriptor_race")

            for fd, expected_info in zip(fds, initial):
                if _identity(os.fstat(fd)) != _identity(expected_info):
                    _fail("descriptor_race")
            for index, component in enumerate(components):
                try:
                    reopened = os.open(component, directory_flags, dir_fd=fds[index])
                except OSError:
                    _fail("descriptor_race")
                try:
                    if _identity(os.fstat(reopened)) != _identity(initial[index + 1]):
                        _fail("descriptor_race")
                finally:
                    os.close(reopened)
            try:
                reopened = os.open("config.toml", file_flags, dir_fd=fds[-1])
            except OSError:
                _fail("descriptor_race")
            try:
                if _identity(os.fstat(reopened)) != _identity(before):
                    _fail("descriptor_race")
            finally:
                os.close(reopened)
            return data
        finally:
            os.close(config_fd)
    finally:
        for fd in reversed(fds):
            os.close(fd)


def _base_line_without_comment(line):
    state = "normal"
    escaped = False
    for index, character in enumerate(line):
        if state == "basic":
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                state = "normal"
        elif state == "literal":
            if character == "'":
                state = "normal"
        elif character == '"':
            state = "basic"
        elif character == "'":
            state = "literal"
        elif character == "#":
            return line[:index]
    if state != "normal" or escaped:
        _fail("base_policy_invalid")
    return line


def _base_key_path(raw):
    position = 0
    parts = []
    while True:
        while position < len(raw) and raw[position] in " \t":
            position += 1
        if position >= len(raw):
            _fail("base_policy_invalid")
        quote = raw[position] if raw[position] in "\"'" else None
        if quote is not None:
            position += 1
            start = position
            while position < len(raw) and raw[position] != quote:
                if raw[position] == "\\" or ord(raw[position]) < 32:
                    _fail("base_policy_invalid")
                position += 1
            if position >= len(raw) or position == start:
                _fail("base_policy_invalid")
            parts.append(raw[start:position])
            position += 1
        else:
            match = _BARE_KEY.match(raw, position)
            if not match:
                _fail("base_policy_invalid")
            parts.append(match.group(0))
            position = match.end()
        while position < len(raw) and raw[position] in " \t":
            position += 1
        if position == len(raw):
            return parts
        if raw[position] != ".":
            _fail("base_policy_invalid")
        position += 1


def _reject_base_mcp_authority(text):
    if '"""' in text or "'''" in text:
        _fail("base_policy_invalid")
    for raw_line in text.splitlines():
        line = _base_line_without_comment(raw_line).strip()
        if not line:
            continue
        if line.startswith("[["):
            if not line.endswith("]]"):
                _fail("base_policy_invalid")
            key_path = _base_key_path(line[2:-2])
        elif line.startswith("["):
            if not line.endswith("]"):
                _fail("base_policy_invalid")
            key_path = _base_key_path(line[1:-1])
        else:
            state = "normal"
            escaped = False
            separator = None
            for index, character in enumerate(line):
                if state == "basic":
                    if escaped:
                        escaped = False
                    elif character == "\\":
                        escaped = True
                    elif character == '"':
                        state = "normal"
                elif state == "literal":
                    if character == "'":
                        state = "normal"
                elif character == '"':
                    state = "basic"
                elif character == "'":
                    state = "literal"
                elif character == "=":
                    separator = index
                    break
            if separator is None:
                _fail("base_policy_invalid")
            key_path = _base_key_path(line[:separator])
        if key_path[0] == "mcp_servers":
            _fail("base_policy_invalid")


def _read_base_policy(path, expected_sha256):
    if not isinstance(expected_sha256, str) or not re.fullmatch(r"[0-9a-f]{64}", expected_sha256):
        _fail("base_policy_digest_mismatch")
    if (not isinstance(path, str) or "\x00" in path or not path.startswith("/") or
            os.path.normpath(path) != path):
        _fail("base_policy_invalid")
    try:
        info = os.lstat(path)
        if not stat.S_ISREG(info.st_mode):
            _fail("base_policy_invalid")
        fd = os.open(path, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW)
    except OSError:
        _fail("base_policy_invalid")
    try:
        data = _read_all(fd)
        if _identity(os.fstat(fd)) != _identity(info):
            _fail("base_policy_invalid")
    finally:
        os.close(fd)
    if _digest(data) != expected_sha256:
        _fail("base_policy_digest_mismatch")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        _fail("base_policy_invalid")
    if (b"\x00" in data or b"\r" in data or data.startswith(b"\xef\xbb\xbf") or
            BEGIN_MARKER.encode() in data or END_MARKER.encode() in data or
            (data and not data.endswith(b"\n"))):
        _fail("base_policy_invalid")
    _reject_base_mcp_authority(text)
    return data


def _directory_identity(info):
    return (info.st_dev, info.st_ino, stat.S_IFMT(info.st_mode), stat.S_IMODE(info.st_mode),
            info.st_uid, info.st_gid)


def _check_output_directory(path, directory_fd, expected_identity, expected_uid):
    try:
        named = os.lstat(path)
        held = os.fstat(directory_fd)
    except OSError:
        _fail("output_invalid")
    if (_identity(named) != _identity(held) or _directory_identity(held) != expected_identity or
            not stat.S_ISDIR(held.st_mode) or stat.S_ISLNK(named.st_mode) or
            held.st_uid != expected_uid or stat.S_IMODE(held.st_mode) != 0o700):
        _fail("output_invalid")


def _open_output_directory(path, expected_uid):
    if (not isinstance(path, str) or "\x00" in path or not path.startswith("/") or
            os.path.normpath(path) != path):
        _fail("output_invalid")
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW
    directory_fd = None
    try:
        named = os.lstat(path)
        directory_fd = os.open(path, flags)
        held = os.fstat(directory_fd)
    except OSError:
        if directory_fd is not None:
            os.close(directory_fd)
        _fail("output_invalid")
    identity = _directory_identity(held)
    try:
        if (_identity(named) != _identity(held) or not stat.S_ISDIR(held.st_mode) or
                stat.S_ISLNK(named.st_mode) or held.st_uid != expected_uid or
                stat.S_IMODE(held.st_mode) != 0o700):
            _fail("output_invalid")
        for name in ("codex-config.toml", "codex-mcp-catalog.json"):
            try:
                os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
            except FileNotFoundError:
                continue
            except OSError:
                _fail("output_invalid")
            _fail("output_exists")
        return directory_fd, identity
    except MappingError:
        os.close(directory_fd)
        raise


def _unlink_bound_entry(directory_fd, name, expected_inode):
    try:
        current = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
    except FileNotFoundError:
        return False
    except OSError:
        return False
    if _inode_identity(current) != expected_inode:
        return False
    try:
        os.unlink(name, dir_fd=directory_fd)
    except OSError:
        return False
    return True


def _read_published(fd, expected_size):
    chunks = []
    remaining = expected_size + 1
    while remaining:
        chunk = os.read(fd, min(8192, remaining))
        if not chunk:
            break
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def _write_atomic(directory, directory_fd, directory_identity, name, data, expected_uid):
    temporary = ".%s.%s.tmp" % (name, uuid.uuid4().hex)
    final_path = os.path.join(directory, name)
    fd = None
    temporary_inode = None
    linked_inode = None
    link_created = False
    completed = False
    try:
        _check_output_directory(directory, directory_fd, directory_identity, expected_uid)
        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW,
                     0o600, dir_fd=directory_fd)
        offset = 0
        while offset < len(data):
            written = os.write(fd, data[offset:])
            if written <= 0:
                _fail("output_invalid")
            offset += written
        os.fchmod(fd, 0o600)
        os.fsync(fd)
        before = os.fstat(fd)
        if (not stat.S_ISREG(before.st_mode) or before.st_uid != expected_uid or
                stat.S_IMODE(before.st_mode) != 0o600 or before.st_nlink != 1 or
                before.st_size != len(data)):
            _fail("output_invalid")
        temporary_inode = _inode_identity(before)
        named_temporary = os.stat(temporary, dir_fd=directory_fd, follow_symlinks=False)
        if _identity(named_temporary) != _identity(before):
            _fail("output_invalid")
        try:
            os.link(temporary, name, src_dir_fd=directory_fd, dst_dir_fd=directory_fd,
                    follow_symlinks=False)
        except FileExistsError:
            _fail("output_exists")
        link_created = True
        final_after_link = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        linked_inode = _inode_identity(final_after_link)
        held_after_link = os.fstat(fd)
        temporary_after_link = os.stat(temporary, dir_fd=directory_fd, follow_symlinks=False)
        if (temporary_inode != _inode_identity(held_after_link) or
                temporary_inode != _inode_identity(temporary_after_link) or
                temporary_inode != linked_inode or held_after_link.st_nlink != 2 or
                _identity(held_after_link) != _identity(temporary_after_link) or
                _identity(held_after_link) != _identity(final_after_link)):
            _fail("output_invalid")
        if not _unlink_bound_entry(directory_fd, temporary, temporary_inode):
            _fail("output_invalid")
        temporary_inode = None
        held_after_unlink = os.fstat(fd)
        final_after_unlink = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
        if (_inode_identity(held_after_unlink) != linked_inode or
                _inode_identity(final_after_unlink) != linked_inode or
                held_after_unlink.st_nlink != 1 or final_after_unlink.st_nlink != 1 or
                _identity(held_after_unlink) != _identity(final_after_unlink)):
            _fail("output_invalid")
        os.fsync(directory_fd)
        _check_output_directory(directory, directory_fd, directory_identity, expected_uid)
        final_fd = os.open(
            name, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK,
            dir_fd=directory_fd)
        try:
            final_before_read = os.fstat(final_fd)
            held_before_read = os.fstat(fd)
            if (not stat.S_ISREG(final_before_read.st_mode) or
                    final_before_read.st_uid != expected_uid or
                    stat.S_IMODE(final_before_read.st_mode) != 0o600 or
                    final_before_read.st_nlink != 1 or final_before_read.st_size != len(data) or
                    _inode_identity(final_before_read) != linked_inode or
                    _identity(final_before_read) != _identity(held_before_read)):
                _fail("output_invalid")
            published = _read_published(final_fd, len(data))
            final_after_read = os.fstat(final_fd)
            held_after_read = os.fstat(fd)
            named_final = os.stat(name, dir_fd=directory_fd, follow_symlinks=False)
            if (_inode_identity(final_before_read) != linked_inode or
                    _identity(final_before_read) != _identity(final_after_read) or
                    _identity(final_after_read) != _identity(held_after_read) or
                    _identity(final_after_read) != _identity(named_final) or
                    final_after_read.st_nlink != 1 or published != data):
                _fail("output_invalid")
        finally:
            os.close(final_fd)
        _check_output_directory(directory, directory_fd, directory_identity, expected_uid)
        completed = True
        return final_path, linked_inode
    except MappingError:
        raise
    except OSError:
        _fail("output_invalid")
    finally:
        if temporary_inode is not None:
            _unlink_bound_entry(directory_fd, temporary, temporary_inode)
        if link_created and not completed:
            cleanup_inode = linked_inode if linked_inode is not None else temporary_inode
            if cleanup_inode is not None:
                _unlink_bound_entry(directory_fd, name, cleanup_inode)
        if fd is not None:
            os.close(fd)


def materialize(d2_record, *, workspace_root, expected_cwd, expected_uid,
                base_policy_path, expected_base_sha256, output_dir,
                mapping_policy_version, required_servers=(), playwright=None):
    """Validate, map, and exclusively publish one secret-free policy generation."""
    candidate = _validate_descriptor(d2_record, workspace_root, expected_cwd, expected_uid)
    output_fd, output_identity = _open_output_directory(output_dir, expected_uid)
    try:
        base_policy = _read_base_policy(base_policy_path, expected_base_sha256)
        config = _read_validated_config(candidate, workspace_root, expected_uid)
        plan = build_mapping(config, mapping_policy_version, required_servers, playwright=playwright)
        if plan["failure"] is not None:
            _fail(plan["failure"])
        policy = base_policy + plan["policy_block"]
        created = []
        try:
            catalog_path, catalog_inode = _write_atomic(
                output_dir, output_fd, output_identity, "codex-mcp-catalog.json",
                plan["catalog_json"], expected_uid)
            created.append(("codex-mcp-catalog.json", catalog_inode))
            policy_path, policy_inode = _write_atomic(
                output_dir, output_fd, output_identity, "codex-config.toml", policy, expected_uid)
            created.append(("codex-config.toml", policy_inode))
        except MappingError:
            for name, inode in created:
                _unlink_bound_entry(output_fd, name, inode)
            try:
                os.fsync(output_fd)
            except OSError:
                pass
            raise
        _check_output_directory(output_dir, output_fd, output_identity, expected_uid)
    finally:
        os.close(output_fd)
    return {
        "schema": SCHEMA,
        "managed_mapping_verified": True,
        "catalog_sha256": plan["catalog_sha256"],
        "mapping_digest": plan["mapping_digest"],
        "policy_sha256": _digest(policy),
        "catalog_path": catalog_path,
        "policy_path": policy_path,
        "path_map": plan["path_map"],
    }
