#!/usr/bin/python3 -I
"""Map one validated per-task Codex managed MCP block into container policy."""

import hashlib
import json
import math
import os
from pathlib import Path
import re
import stat
import uuid


D2_SOURCE_SHA256 = "30f0d4363e4ddafca0d2cb8a49e4807d7ee56da8374a9025add70cf1147dc2d8"
D2_BUILD_SHA256 = "4316863681f5378a5846cdb48ff49ccb49daeff353f5cdbeeab0740f0e4e8bbc"
D2_BINARY_SHA256 = "0e3f16bb910154660d5bc8c22b4e3de16f0a20504d8b79487a70c589f28eb5e3"

BEGIN_MARKER = "# BEGIN multica-managed mcp_servers (do not edit; regenerated by daemon)"
END_MARKER = "# END multica-managed mcp_servers"
SCHEMA = "ALTERA_CODEX_MCP_MAP_V1"
MAX_CONFIG_BYTES = 65536
MAX_STRING_BYTES = 16384
MAX_DEPTH = 16
MAX_CATALOG_BYTES = 8192

_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")
_NUMBER = re.compile(r"-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?")
_POLICY_VERSION = re.compile(r"[A-Za-z0-9._-]{1,128}")
_TRACE_COMMANDS = {
    "/Users/egorbondarenko/.trace/bin/trace",
    "/Users/egorbondarenko/.trace/bin/trace-mcp",
}
_PLAYWRIGHT_ARGS = {
    ("-y", "@playwright/mcp"),
    ("-y", "@playwright/mcp@latest"),
    ("-y", "@playwright/mcp", "--headless"),
    ("-y", "@playwright/mcp@latest", "--headless"),
}
_SECRET_PARTS = ("auth", "cookie", "credential", "env", "header", "password", "secret", "token")


class MappingError(ValueError):
    """A fixed, non-disclosing mapper failure."""

    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _fail(code):
    raise MappingError(code)


def _digest(data):
    return hashlib.sha256(data).hexdigest()


def _canonical_json(value):
    encoded = (json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n").encode()
    if len(encoded) > MAX_CATALOG_BYTES:
        _fail("input_bound_exceeded")
    return encoded


def _decode_config(data):
    if not isinstance(data, bytes) or len(data) > MAX_CONFIG_BYTES:
        _fail("input_bound_exceeded")
    if data.startswith(b"\xef\xbb\xbf") or b"\x00" in data or b"\r" in data:
        _fail("config_encoding_invalid")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        _fail("config_encoding_invalid")
    if (any(ord(character) < 32 and character not in "\t\n" for character in text) or
            any(character in "\u0085\u2028\u2029" for character in text)):
        _fail("config_encoding_invalid")
    return text


def _lexical_markers(text):
    if '\"\"\"' in text or "'''" in text:
        _fail("managed_block_ambiguous")

    recognized = []
    lines = text.splitlines()
    for line_number, line in enumerate(lines):
        if line in (BEGIN_MARKER, END_MARKER):
            recognized.append((line_number, line))
            continue
        state = "normal"
        escaped = False
        square = 0
        curly = 0
        for character in line:
            if state == "comment":
                break
            if state == "basic":
                if escaped:
                    escaped = False
                elif character == "\\":
                    escaped = True
                elif character == '"':
                    state = "normal"
                continue
            if state == "literal":
                if character == "'":
                    state = "normal"
                continue
            if character == "#":
                state = "comment"
            elif character == '"':
                state = "basic"
            elif character == "'":
                state = "literal"
            elif character == "[":
                square += 1
            elif character == "]":
                square -= 1
            elif character == "{":
                curly += 1
            elif character == "}":
                curly -= 1
            if square < 0 or curly < 0:
                _fail("managed_block_ambiguous")
        if state in ("basic", "literal") or escaped or square or curly:
            _fail("managed_block_ambiguous")

    raw_begin = text.count(BEGIN_MARKER)
    raw_end = text.count(END_MARKER)
    if not recognized and raw_begin == 0 and raw_end == 0:
        return None
    if raw_begin != 1 or raw_end != 1 or len(recognized) != 2:
        _fail("managed_block_invalid")
    if recognized[0][1] != BEGIN_MARKER or recognized[1][1] != END_MARKER:
        _fail("managed_block_invalid")
    begin_index, end_index = recognized[0][0], recognized[1][0]
    if begin_index >= end_index:
        _fail("managed_block_invalid")
    nonblank = [index for index, line in enumerate(lines) if line.strip()]
    if not text.endswith("\n") or not nonblank or nonblank[-1] != end_index:
        _fail("managed_block_invalid")
    return lines[begin_index + 1:end_index]


class _ValueParser:
    def __init__(self, value):
        self.value = value
        self.position = 0

    def parse(self):
        result = self._value(1)
        self._spaces()
        if self.position != len(self.value):
            _fail("managed_value_invalid")
        return result

    def _spaces(self):
        while self.position < len(self.value) and self.value[self.position] in " \t":
            self.position += 1

    def _value(self, depth):
        if depth > MAX_DEPTH:
            _fail("input_bound_exceeded")
        self._spaces()
        if self.position >= len(self.value):
            _fail("managed_value_invalid")
        current = self.value[self.position]
        if current == '"':
            return self._string()
        if current == "[":
            return self._array(depth)
        if current == "{":
            return self._inline_table(depth)
        for literal, result in (("true", True), ("false", False)):
            if self.value.startswith(literal, self.position):
                self.position += len(literal)
                return result
        match = _NUMBER.match(self.value, self.position)
        if not match:
            _fail("managed_value_invalid")
        token = match.group(0)
        self.position = match.end()
        try:
            if "." in token or "e" in token.lower():
                number = float(token)
                if not math.isfinite(number):
                    _fail("managed_value_invalid")
                return number
            return int(token)
        except (OverflowError, ValueError):
            _fail("managed_value_invalid")

    def _string(self):
        self.position += 1
        pieces = []
        escapes = {"b": "\b", "t": "\t", "n": "\n", "f": "\f", "r": "\r", '"': '"', "\\": "\\"}
        while self.position < len(self.value):
            character = self.value[self.position]
            self.position += 1
            if character == '"':
                decoded = "".join(pieces)
                try:
                    size = len(decoded.encode("utf-8"))
                except UnicodeEncodeError:
                    _fail("managed_value_invalid")
                if size > MAX_STRING_BYTES:
                    _fail("input_bound_exceeded")
                return decoded
            if character == "\\":
                if self.position >= len(self.value):
                    _fail("managed_value_invalid")
                escape = self.value[self.position]
                self.position += 1
                if escape in escapes:
                    pieces.append(escapes[escape])
                    continue
                if escape in ("u", "U"):
                    width = 4 if escape == "u" else 8
                    raw = self.value[self.position:self.position + width]
                    if len(raw) != width or not re.fullmatch(r"[0-9A-Fa-f]+", raw):
                        _fail("managed_value_invalid")
                    self.position += width
                    try:
                        character = chr(int(raw, 16))
                        character.encode("utf-8")
                    except (ValueError, UnicodeEncodeError):
                        _fail("managed_value_invalid")
                    pieces.append(character)
                    continue
                _fail("managed_value_invalid")
            elif ord(character) < 32:
                _fail("managed_value_invalid")
            else:
                pieces.append(character)
        _fail("managed_value_invalid")

    def _array(self, depth):
        self.position += 1
        result = []
        self._spaces()
        if self.position < len(self.value) and self.value[self.position] == "]":
            self.position += 1
            return result
        while True:
            result.append(self._value(depth + 1))
            self._spaces()
            if self.position >= len(self.value):
                _fail("managed_value_invalid")
            if self.value[self.position] == "]":
                self.position += 1
                return result
            if self.value[self.position] != ",":
                _fail("managed_value_invalid")
            self.position += 1
            self._spaces()
            if self.position >= len(self.value) or self.value[self.position] == "]":
                _fail("managed_value_invalid")

    def _inline_table(self, depth):
        self.position += 1
        result = {}
        self._spaces()
        if self.position < len(self.value) and self.value[self.position] == "}":
            self.position += 1
            return result
        while True:
            match = _BARE_KEY.match(self.value, self.position)
            if not match:
                _fail("managed_value_invalid")
            key = match.group(0)
            self.position = match.end()
            if not self.value.startswith(" = ", self.position) or key in result:
                _fail("managed_value_invalid")
            self.position += 3
            result[key] = self._value(depth + 1)
            self._spaces()
            if self.position >= len(self.value):
                _fail("managed_value_invalid")
            if self.value[self.position] == "}":
                self.position += 1
                return result
            if self.value[self.position] != ",":
                _fail("managed_value_invalid")
            self.position += 1
            self._spaces()
            if self.position >= len(self.value) or self.value[self.position] == "}":
                _fail("managed_value_invalid")


def _parse_managed(data):
    text = _decode_config(data)
    lines = _lexical_markers(text)
    if lines is None:
        return None
    tables = {}
    current = None
    for line in lines:
        if not line:
            continue
        table = re.fullmatch(r"\[mcp_servers\.([A-Za-z0-9_-]+)\]", line)
        if table:
            current = table.group(1)
            if current in tables or len(tables) >= 3:
                _fail("managed_block_invalid")
            tables[current] = {}
            continue
        assignment = re.fullmatch(r"([A-Za-z0-9_-]+) = (.+)", line)
        if not assignment or current is None:
            _fail("managed_value_invalid")
        key, raw_value = assignment.groups()
        if key in tables[current]:
            _fail("managed_value_invalid")
        tables[current][key] = _ValueParser(raw_value).parse()
    return tables


def _server_rows():
    return [
        {"name": "context7", "present": False, "shape": "absent", "mapping_ready": False},
        {"name": "playwright", "present": False, "shape": "absent", "mapping_ready": False},
        {"name": "trace", "present": False, "shape": "absent", "mapping_ready": False},
    ]


def _secret_key(key):
    lowered = key.lower()
    return any(part in lowered for part in _SECRET_PARTS)


def _render_block(ready):
    lines = [BEGIN_MARKER]
    first = True
    for name in ("context7", "trace"):
        if name not in ready:
            continue
        if not first:
            lines.append("")
        first = False
        lines.append("[mcp_servers.%s]" % name)
        if name == "context7":
            lines.extend(("experimental_use_rmcp_client = true", 'url = "https://mcp.context7.com/mcp"'))
        else:
            lines.extend(('command = "/usr/local/bin/trace-mcp"', 'args = ["serve"]'))
    lines.append(END_MARKER)
    return ("\n".join(lines) + "\n").encode()


def build_mapping(data, mapping_policy_version, required_servers=()):
    """Parse and classify managed TOML bytes without filesystem access."""
    if not isinstance(mapping_policy_version, str) or not _POLICY_VERSION.fullmatch(mapping_policy_version):
        _fail("mapping_policy_invalid")
    if (not isinstance(required_servers, (tuple, list)) or
            any(name not in ("context7", "playwright", "trace") for name in required_servers) or
            len(required_servers) != len(set(required_servers))):
        _fail("required_roster_invalid")

    tables = _parse_managed(data)
    rows = _server_rows()
    catalog = {
        "schema": SCHEMA,
        "managed_state": "unresolved" if tables is None else ("explicit_empty" if not tables else "explicit_nonempty"),
        "descriptor_valid": True,
        "unknown_servers_present": False,
        "unknown_fields_present": False,
        "secret_fields_present": False,
        "servers": rows,
        "managed_mapping_verified": False,
    }
    failure = None
    path_map = {}
    ready = set()
    if tables is None:
        failure = "managed_config_absent"
    else:
        by_name = {row["name"]: row for row in rows}
        for name, fields in tables.items():
            if name not in by_name:
                catalog["unknown_servers_present"] = True
                catalog["unknown_fields_present"] = bool(fields) or catalog["unknown_fields_present"]
                catalog["secret_fields_present"] = (catalog["secret_fields_present"] or
                                                     any(_secret_key(key) for key in fields))
                failure = "unverified_managed_config"
                continue
            row = by_name[name]
            row["present"] = True
            unknown = False
            if name == "context7":
                expected = {"experimental_use_rmcp_client", "url"}
                valid = (set(fields) == expected and fields.get("experimental_use_rmcp_client") is True and
                         fields.get("url") == "https://mcp.context7.com/mcp")
                shape = "context7_public_mcp"
            elif name == "trace":
                expected = {"command", "args"}
                valid = (set(fields) == expected and fields.get("command") in _TRACE_COMMANDS and
                         fields.get("args") == ["serve"])
                shape = "trace_serve"
            else:
                expected = {"command", "args"}
                valid = (set(fields) == expected and fields.get("command") == "npx" and
                         isinstance(fields.get("args"), list) and tuple(fields["args"]) in _PLAYWRIGHT_ARGS)
                shape = "playwright_dynamic_npx"
            if set(fields) - expected:
                unknown = True
                catalog["unknown_fields_present"] = True
                catalog["secret_fields_present"] = (catalog["secret_fields_present"] or
                                                     any(_secret_key(key) for key in set(fields) - expected))
            if valid and name != "playwright":
                row.update(shape=shape, mapping_ready=True)
                ready.add(name)
                if name == "trace":
                    path_map[fields["command"]] = "/usr/local/bin/trace-mcp"
            elif valid:
                row.update(shape=shape, mapping_ready=False)
                failure = failure or "mapping_not_ready"
            else:
                row.update(shape="unverified", mapping_ready=False)
                failure = "unverified_managed_config"
                if unknown:
                    catalog["unknown_fields_present"] = True

        if failure is None:
            if any(not by_name[name]["present"] or not by_name[name]["mapping_ready"] for name in required_servers):
                failure = "required_server_missing"
            else:
                catalog["managed_mapping_verified"] = True

    catalog_json = _canonical_json(catalog)
    block = _render_block(ready) if failure is None else None
    return {
        "catalog": catalog,
        "catalog_json": catalog_json,
        "catalog_sha256": _digest(catalog_json),
        "mapping_digest": _digest(catalog_json + b"\x00" + mapping_policy_version.encode()),
        "path_map": path_map,
        "policy_block": block,
        "failure": failure,
    }


def _identity(info):
    return (info.st_dev, info.st_ino, stat.S_IFMT(info.st_mode), stat.S_IMODE(info.st_mode),
            info.st_uid, info.st_gid, info.st_nlink, info.st_size, info.st_mtime_ns, info.st_ctime_ns)


def _read_all(fd):
    chunks = []
    total = 0
    while True:
        try:
            chunk = os.read(fd, min(8192, MAX_CONFIG_BYTES + 1 - total))
        except BlockingIOError:
            _fail("config_metadata_invalid")
        if not chunk:
            break
        chunks.append(chunk)
        total += len(chunk)
        if total > MAX_CONFIG_BYTES:
            _fail("input_bound_exceeded")
    return b"".join(chunks)


def _validate_descriptor(record, workspace_root, expected_cwd, expected_uid):
    if not isinstance(expected_uid, int) or isinstance(expected_uid, bool) or expected_uid < 0:
        _fail("descriptor_invalid")
    if not isinstance(record, dict) or record.get("binary_sha256") != D2_BINARY_SHA256:
        _fail("descriptor_invalid")
    descriptor = record.get("descriptor")
    if not isinstance(descriptor, dict):
        _fail("descriptor_invalid")
    expected = {
        "source_sha256": D2_SOURCE_SHA256,
        "build_sha256": D2_BUILD_SHA256,
        "read_status": "lexical_candidate",
        "canonical_identity": "not_checked",
        "task_acceptance": "not_checked",
        "cwd_matches_expected": True,
    }
    if any(descriptor.get(key) != value for key, value in expected.items()):
        _fail("descriptor_invalid")
    if not isinstance(descriptor.get("argc"), int) or isinstance(descriptor.get("argc"), bool):
        _fail("descriptor_invalid")
    for value in (workspace_root, expected_cwd):
        if not isinstance(value, str) or not value.startswith("/") or os.path.normpath(value) != value:
            _fail("descriptor_invalid")
    if os.getcwd() != expected_cwd:
        _fail("descriptor_invalid")
    candidate = descriptor.get("candidate_path")
    if not isinstance(candidate, str) or len(candidate.encode("utf-8")) > 1024:
        _fail("descriptor_invalid")
    pattern = re.escape(workspace_root) + r"/alte-[0-9]{1,9}-[0-9a-f]{12}/codex-home"
    if not re.fullmatch(pattern, candidate):
        _fail("descriptor_invalid")
    return candidate


def _read_validated_config(candidate, workspace_root, expected_uid):
    components = candidate[1:].split("/")
    workspace_components = workspace_root[1:].split("/")
    if components[:len(workspace_components)] != workspace_components:
        _fail("descriptor_invalid")
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW
    file_flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK
    fds = []
    initial = []
    try:
        try:
            fds.append(os.open("/", directory_flags))
            initial.append(os.fstat(fds[-1]))
            for index, component in enumerate(components):
                fd = os.open(component, directory_flags, dir_fd=fds[-1])
                info = os.fstat(fd)
                if not stat.S_ISDIR(info.st_mode):
                    os.close(fd)
                    _fail("descriptor_invalid")
                if index + 1 >= len(workspace_components):
                    if info.st_uid != expected_uid or stat.S_IMODE(info.st_mode) & 0o022:
                        os.close(fd)
                        _fail("descriptor_invalid")
                fds.append(fd)
                initial.append(info)
        except (OSError, ValueError):
            _fail("descriptor_invalid")

        try:
            config_fd = os.open("config.toml", file_flags, dir_fd=fds[-1])
        except OSError:
            _fail("config_metadata_invalid")
        try:
            before = os.fstat(config_fd)
            if (not stat.S_ISREG(before.st_mode) or before.st_uid != expected_uid or
                    stat.S_IMODE(before.st_mode) != 0o600 or before.st_nlink != 1 or
                    before.st_size > MAX_CONFIG_BYTES):
                _fail("config_metadata_invalid")
            data = _read_all(config_fd)
            after = os.fstat(config_fd)
            if _identity(after) != _identity(before) or len(data) != before.st_size:
                _fail("descriptor_race")

            for fd, expected_info in zip(fds, initial):
                if _identity(os.fstat(fd)) != _identity(expected_info):
                    _fail("descriptor_race")
            for index, component in enumerate(components):
                try:
                    reopened = os.open(component, directory_flags, dir_fd=fds[index])
                except OSError:
                    _fail("descriptor_race")
                try:
                    if _identity(os.fstat(reopened)) != _identity(initial[index + 1]):
                        _fail("descriptor_race")
                finally:
                    os.close(reopened)
            try:
                reopened = os.open("config.toml", file_flags, dir_fd=fds[-1])
            except OSError:
                _fail("descriptor_race")
            try:
                if _identity(os.fstat(reopened)) != _identity(before):
                    _fail("descriptor_race")
            finally:
                os.close(reopened)
            return data
        finally:
            os.close(config_fd)
    finally:
        for fd in reversed(fds):
            os.close(fd)


def _read_base_policy(path, expected_sha256):
    if not isinstance(expected_sha256, str) or not re.fullmatch(r"[0-9a-f]{64}", expected_sha256):
        _fail("base_policy_digest_mismatch")
    try:
        info = os.lstat(path)
        if not stat.S_ISREG(info.st_mode):
            _fail("base_policy_invalid")
        fd = os.open(path, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW)
    except OSError:
        _fail("base_policy_invalid")
    try:
        data = _read_all(fd)
        if _identity(os.fstat(fd)) != _identity(info):
            _fail("base_policy_invalid")
    finally:
        os.close(fd)
    if _digest(data) != expected_sha256:
        _fail("base_policy_digest_mismatch")
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        _fail("base_policy_invalid")
    if (b"\x00" in data or b"\r" in data or data.startswith(b"\xef\xbb\xbf") or
            BEGIN_MARKER.encode() in data or END_MARKER.encode() in data or b"[mcp_servers" in data or
            (data and not data.endswith(b"\n"))):
        _fail("base_policy_invalid")
    return data


def _validate_output_directory(path, expected_uid):
    try:
        info = os.lstat(path)
    except OSError:
        _fail("output_invalid")
    if (not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode) or info.st_uid != expected_uid or
            stat.S_IMODE(info.st_mode) != 0o700):
        _fail("output_invalid")
    for name in ("codex-config.toml", "codex-mcp-catalog.json"):
        try:
            os.lstat(os.path.join(path, name))
        except FileNotFoundError:
            continue
        except OSError:
            _fail("output_invalid")
        _fail("output_exists")


def _write_atomic(directory, name, data, expected_uid):
    temporary = ".%s.%s.tmp" % (name, uuid.uuid4().hex)
    temporary_path = os.path.join(directory, temporary)
    final_path = os.path.join(directory, name)
    fd = None
    linked = False
    completed = False
    try:
        fd = os.open(temporary_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW, 0o600)
        offset = 0
        while offset < len(data):
            written = os.write(fd, data[offset:])
            if written <= 0:
                _fail("output_invalid")
            offset += written
        os.fchmod(fd, 0o600)
        os.fsync(fd)
        before = os.fstat(fd)
        if (not stat.S_ISREG(before.st_mode) or before.st_uid != expected_uid or
                stat.S_IMODE(before.st_mode) != 0o600 or before.st_nlink != 1 or
                before.st_size != len(data)):
            _fail("output_invalid")
        os.close(fd)
        fd = None
        try:
            os.link(temporary_path, final_path, follow_symlinks=False)
        except FileExistsError:
            _fail("output_exists")
        linked = True
        os.unlink(temporary_path)
        temporary_path = None
        directory_fd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
        final = os.lstat(final_path)
        if (not stat.S_ISREG(final.st_mode) or final.st_uid != expected_uid or
                stat.S_IMODE(final.st_mode) != 0o600 or final.st_nlink != 1 or
                final.st_size != len(data)):
            _fail("output_invalid")
        completed = True
        return final_path
    except MappingError:
        raise
    except OSError:
        _fail("output_invalid")
    finally:
        if fd is not None:
            os.close(fd)
        if temporary_path is not None:
            try:
                os.unlink(temporary_path)
            except FileNotFoundError:
                pass
        if linked and not completed:
            try:
                os.unlink(final_path)
            except OSError:
                pass


def materialize(d2_record, *, workspace_root, expected_cwd, expected_uid,
                base_policy_path, expected_base_sha256, output_dir,
                mapping_policy_version, required_servers=()):
    """Validate, map, and exclusively publish one secret-free policy generation."""
    candidate = _validate_descriptor(d2_record, workspace_root, expected_cwd, expected_uid)
    _validate_output_directory(output_dir, expected_uid)
    base_policy = _read_base_policy(base_policy_path, expected_base_sha256)
    config = _read_validated_config(candidate, workspace_root, expected_uid)
    plan = build_mapping(config, mapping_policy_version, required_servers)
    if plan["failure"] is not None:
        _fail(plan["failure"])
    policy = base_policy + plan["policy_block"]
    created = []
    try:
        catalog_path = _write_atomic(output_dir, "codex-mcp-catalog.json", plan["catalog_json"], expected_uid)
        created.append(catalog_path)
        policy_path = _write_atomic(output_dir, "codex-config.toml", policy, expected_uid)
        created.append(policy_path)
    except MappingError:
        for path in created:
            try:
                os.unlink(path)
            except OSError:
                pass
        raise
    return {
        "schema": SCHEMA,
        "managed_mapping_verified": True,
        "catalog_sha256": plan["catalog_sha256"],
        "mapping_digest": plan["mapping_digest"],
        "policy_sha256": _digest(policy),
        "catalog_path": catalog_path,
        "policy_path": policy_path,
        "path_map": plan["path_map"],
    }
