"""Synthetic tests for the trusted Codex managed-TOML mapper."""

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import stat
import tempfile
import traceback
import unittest
from unittest import mock

ROOT = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location("codex_toml_map", ROOT / "codex_toml_map.py")
mapper = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(mapper)


BEGIN = "# BEGIN multica-managed mcp_servers (do not edit; regenerated by daemon)"
END = "# END multica-managed mcp_servers"
BASE_POLICY = b'model = "gpt-5.6-terra"\nmodel_reasoning_effort = "medium"\n'


def managed(*lines):
    return ("\n".join((BEGIN,) + lines + (END,)) + "\n").encode()


class MappingFixture:
    def __init__(self):
        self.temp = tempfile.TemporaryDirectory(prefix="altera-codex-map-", dir="/private/tmp")
        self.root = Path(self.temp.name)
        self.workspace = self.root / "workspace"
        self.home = self.workspace / "alte-1-012345abcdef" / "codex-home"
        self.home.mkdir(parents=True)
        os.chmod(self.workspace, 0o755)
        os.chmod(self.home.parent, 0o755)
        os.chmod(self.home, 0o755)
        self.config = self.home / "config.toml"
        self.base = self.root / "base.toml"
        self.base.write_bytes(BASE_POLICY)
        os.chmod(self.base, 0o600)
        self.output = self.root / "generation"
        self.output.mkdir(mode=0o700)
        self.uid = os.getuid()

    def close(self):
        self.temp.cleanup()

    def write_config(self, data):
        self.config.write_bytes(data)
        os.chmod(self.config, 0o600)

    def record(self, candidate=None, **overrides):
        descriptor = {
            "candidate_path": str(candidate or self.home),
            "source_sha256": mapper.D2_SOURCE_SHA256,
            "build_sha256": mapper.D2_BUILD_SHA256,
            "read_status": "lexical_candidate",
            "canonical_identity": "not_checked",
            "task_acceptance": "not_checked",
            "cwd_matches_expected": True,
            "argc": 4,
        }
        descriptor.update(overrides)
        return {"binary_sha256": mapper.D2_BINARY_SHA256, "descriptor": descriptor}

    def materialize(self, data, required=(), record=None, **kwargs):
        self.write_config(data)
        return mapper.materialize(
            record or self.record(),
            workspace_root=str(self.workspace),
            expected_cwd=os.getcwd(),
            expected_uid=self.uid,
            base_policy_path=str(self.base),
            expected_base_sha256=hashlib.sha256(BASE_POLICY).hexdigest(),
            output_dir=str(self.output),
            mapping_policy_version="codex-mcp-map-v1",
            required_servers=required,
            **kwargs,
        )


class CodexTomlMappingTests(unittest.TestCase):
    def setUp(self):
        self.fixture = MappingFixture()
        self.addCleanup(self.fixture.close)

    def test_context7_and_trace_materialize_exact_redacted_outputs(self):
        native_trace = "/Users/egorbondarenko/.trace/bin/trace"
        data = b'[mcp_servers.inherited]\ncommand = "DO_NOT_COPY"\n\n' + managed(
            "[mcp_servers.context7]",
            "experimental_use_rmcp_client = true",
            'url = "https://mcp.context7.com/mcp"',
            "",
            "[mcp_servers.trace]",
            'args = ["serve"]',
            'command = "' + native_trace + '"',
        )
        config_before = data
        result = self.fixture.materialize(data, required=("context7", "trace"))

        expected_policy = BASE_POLICY + managed(
            "[mcp_servers.context7]",
            "experimental_use_rmcp_client = true",
            'url = "https://mcp.context7.com/mcp"',
            "",
            "[mcp_servers.trace]",
            'command = "/usr/local/bin/trace-mcp"',
            'args = ["serve"]',
        )
        self.assertEqual((self.fixture.output / "codex-config.toml").read_bytes(), expected_policy)
        catalog_bytes = (self.fixture.output / "codex-mcp-catalog.json").read_bytes()
        expected_catalog = {
            "descriptor_valid": True,
            "managed_mapping_verified": True,
            "managed_state": "explicit_nonempty",
            "schema": "ALTERA_CODEX_MCP_MAP_V1",
            "secret_fields_present": False,
            "servers": [
                {"mapping_ready": True, "name": "context7", "present": True,
                 "shape": "context7_public_mcp"},
                {"mapping_ready": False, "name": "playwright", "present": False,
                 "shape": "absent"},
                {"mapping_ready": True, "name": "trace", "present": True,
                 "shape": "trace_serve"},
            ],
            "unknown_fields_present": False,
            "unknown_servers_present": False,
        }
        literal_catalog = (json.dumps(expected_catalog, sort_keys=True, separators=(",", ":")) + "\n").encode()
        self.assertEqual(catalog_bytes, literal_catalog)
        self.assertNotIn(native_trace.encode(), catalog_bytes)
        self.assertNotIn(b"DO_NOT_COPY", expected_policy)
        self.assertEqual(result["path_map"], {native_trace: "/usr/local/bin/trace-mcp"})
        self.assertEqual(result["managed_mapping_verified"], True)
        self.assertEqual(stat.S_IMODE((self.fixture.output / "codex-config.toml").stat().st_mode), 0o600)
        self.assertEqual(stat.S_IMODE((self.fixture.output / "codex-mcp-catalog.json").stat().st_mode), 0o600)
        self.assertEqual(self.fixture.config.read_bytes(), config_before)

    def test_explicit_empty_is_distinct_from_absent_and_required_roster(self):
        empty = mapper.build_mapping(managed(), "codex-mcp-map-v1")
        self.assertEqual(empty["failure"], None)
        self.assertEqual(empty["catalog"]["managed_state"], "explicit_empty")
        self.assertTrue(empty["catalog"]["managed_mapping_verified"])
        self.assertEqual(empty["policy_block"], managed())

        absent = mapper.build_mapping(b'model = "gpt-5.6-terra"\n', "codex-mcp-map-v1")
        self.assertEqual(absent["failure"], "managed_config_absent")
        self.assertEqual(absent["catalog"]["managed_state"], "unresolved")
        self.assertFalse(absent["catalog"]["managed_mapping_verified"])

        with self.assertRaisesRegex(mapper.MappingError, "^required_server_missing$"):
            self.fixture.materialize(managed(), required=("trace",))
        self.assertEqual(list(self.fixture.output.iterdir()), [])

    def test_lexical_guard_and_marker_state_fail_closed(self):
        ambiguous = [
            (BEGIN + '\nvalue = """' + END + '"""\n' + END + "\n").encode(),
            ("value = [\n1]\n" + BEGIN + "\n" + END + "\n").encode(),
            ("value = \"unterminated\n" + BEGIN + "\n" + END + "\n").encode(),
        ]
        for data in ambiguous:
            with self.subTest(data=data[:20]):
                with self.assertRaisesRegex(mapper.MappingError, "^managed_block_ambiguous$"):
                    mapper.build_mapping(data, "codex-mcp-map-v1")

        invalid = [
            (BEGIN + "\n").encode(),
            (END + "\n" + BEGIN + "\n").encode(),
            managed() + managed(),
            managed() + b'model = "after"\n',
            (" # " + BEGIN + "\n" + END + "\n").encode(),
        ]
        for data in invalid:
            with self.subTest(data=data[:20]):
                with self.assertRaisesRegex(mapper.MappingError, "^managed_block_invalid$"):
                    mapper.build_mapping(data, "codex-mcp-map-v1")

        for data in [b"\xef\xbb\xbf" + managed(), managed() + b"\r", managed() + b"\x00", b"\xff",
                     managed() + "separator\u2028".encode()]:
            with self.subTest(data=data[-4:]):
                with self.assertRaisesRegex(mapper.MappingError, "^config_encoding_invalid$"):
                    mapper.build_mapping(data, "codex-mcp-map-v1")

    def test_value_parser_rejects_forbidden_syntax_and_bounds(self):
        invalid_values = [
            "when = 2026-09-14",
            "literal = 'value'",
            "dotted.key = true",
            "array = [1,]",
            "number = nan",
            "value=true",
        ]
        for line in invalid_values:
            data = managed("[mcp_servers.context7]", line)
            with self.subTest(line=line):
                with self.assertRaisesRegex(mapper.MappingError, "^managed_value_invalid$"):
                    mapper.build_mapping(data, "codex-mcp-map-v1")

        too_deep = "value = " + "[" * 17 + "true" + "]" * 17
        too_long = 'value = "' + "x" * 16385 + '"'
        for line in [too_deep, too_long]:
            with self.assertRaisesRegex(mapper.MappingError, "^input_bound_exceeded$"):
                mapper.build_mapping(managed("[mcp_servers.context7]", line), "codex-mcp-map-v1")
        with self.assertRaisesRegex(mapper.MappingError, "^input_bound_exceeded$"):
            mapper.build_mapping(b"x" * 65537, "codex-mcp-map-v1")

    def test_context7_variants_are_rejected_without_secret_disclosure(self):
        secret = "SECRET_CONTEXT7_CANARY_74f4"
        variants = [
            ("url", 'url = "https://mcp.context7.com/mcp?token=' + secret + '"'),
            ("header", 'http_headers = { Authorization = "' + secret + '" }'),
            ("env", 'env = { TOKEN = "' + secret + '" }'),
            ("unknown", 'future_field = "' + secret + '"'),
        ]
        for kind, line in variants:
            data = managed("[mcp_servers.context7]", "experimental_use_rmcp_client = true", line)
            plan = mapper.build_mapping(data, "codex-mcp-map-v1")
            encoded = plan["catalog_json"]
            self.assertEqual(plan["failure"], "unverified_managed_config")
            self.assertNotIn(secret.encode(), encoded)
            self.assertNotIn(hashlib.sha256(secret.encode()).hexdigest().encode(), encoded)
            if kind in ("header", "env"):
                self.assertTrue(plan["catalog"]["secret_fields_present"])

    def test_trace_accepts_only_two_absolute_identities_and_serve(self):
        for name in ("trace", "trace-mcp"):
            native = "/Users/egorbondarenko/.trace/bin/" + name
            plan = mapper.build_mapping(managed(
                "[mcp_servers.trace]", 'command = "' + native + '"', 'args = ["serve"]'),
                "codex-mcp-map-v1", required_servers=("trace",))
            self.assertIsNone(plan["failure"])
            self.assertEqual(plan["path_map"], {native: "/usr/local/bin/trace-mcp"})

        for command, args, extra in [
            ("trace", '["serve"]', ()),
            ("/usr/local/bin/trace", '["serve"]', ()),
            ("/Users/egorbondarenko/.trace/bin/trace", '["serve", "--preset", "review"]', ()),
            ("/Users/egorbondarenko/.trace/bin/trace", '["serve"]', ('env = { X = "Y" }',)),
        ]:
            plan = mapper.build_mapping(managed(
                "[mcp_servers.trace]", 'command = "' + command + '"', "args = " + args, *extra),
                "codex-mcp-map-v1")
            self.assertEqual(plan["failure"], "unverified_managed_config")

    def test_playwright_forms_are_classified_but_never_ready(self):
        arg_sets = [
            ["-y", "@playwright/mcp"],
            ["-y", "@playwright/mcp@latest"],
            ["-y", "@playwright/mcp", "--headless"],
            ["-y", "@playwright/mcp@latest", "--headless"],
        ]
        for args in arg_sets:
            rendered = ", ".join(json.dumps(item) for item in args)
            plan = mapper.build_mapping(managed(
                "[mcp_servers.playwright]", 'command = "npx"', "args = [" + rendered + "]"),
                "codex-mcp-map-v1")
            row = plan["catalog"]["servers"][1]
            self.assertEqual(row, {"name": "playwright", "present": True,
                                  "shape": "playwright_dynamic_npx", "mapping_ready": False})
            self.assertEqual(plan["failure"], "mapping_not_ready")
            self.assertEqual(plan["path_map"], {})
            self.assertIsNone(plan["policy_block"])

    def test_playwright_requires_private_pinned_receipt_and_exact_image(self):
        receipt_dir = self.fixture.root / 'receipt'; receipt_dir.mkdir(mode=0o700)
        receipt = receipt_dir / 'accepted.json'
        image = 'sha256:' + 'a' * 64
        data = managed('[mcp_servers.playwright]', 'command = "npx"', 'args = ["-y", "@playwright/mcp@latest"]')
        record = mapper.playwright_receipt_template(image)
        record['artifacts'] = {key: 'b' * 64 for key in mapper.PLAYWRIGHT_ARTIFACTS}
        record['checks'] = {key: 'c' * 64 for key in mapper.PLAYWRIGHT_CHECKS}
        receipt.write_bytes(mapper._canonical_json(record)); receipt.chmod(0o600)
        reference = {'path': str(receipt), 'sha256': hashlib.sha256(receipt.read_bytes()).hexdigest(), 'image': image}
        plan = mapper.build_mapping(data, 'pw-v1', playwright=reference)
        self.assertTrue(plan['catalog']['servers'][1]['mapping_ready'])
        self.assertEqual(plan['catalog']['servers'][1]['shape'], 'playwright_static_0_0_80')
        tables = mapper._parse_managed(plan['policy_block'])
        self.assertEqual(tables['playwright'], {'command': '/usr/bin/env', 'args': mapper.PLAYWRIGHT_VECTOR[1:]})
        for bad in [True, {**reference, 'image': 'sha256:' + 'd' * 64}, {**reference, 'sha256': 'e' * 64}]:
            with self.assertRaisesRegex(mapper.MappingError, '^playwright_attestation_invalid$'):
                mapper.build_mapping(data, 'pw-v1', playwright=bad)
        receipt.chmod(0o644)
        with mock.patch.object(mapper.os, 'read', side_effect=AssertionError('read before metadata')):
            with self.assertRaisesRegex(mapper.MappingError, '^playwright_attestation_invalid$'):
                mapper.build_mapping(data, 'pw-v1', playwright=reference)

    def test_unknown_server_and_fields_are_presence_only_and_bounded(self):
        secret_name = "unknown_SECRET_server_9182"
        secret_value = "SECRET_VALUE_5da9"
        plan = mapper.build_mapping(managed(
            "[mcp_servers." + secret_name + "]", 'token = "' + secret_value + '"'),
            "codex-mcp-map-v1")
        encoded = plan["catalog_json"]
        self.assertEqual(plan["failure"], "unverified_managed_config")
        self.assertTrue(plan["catalog"]["unknown_servers_present"])
        self.assertTrue(plan["catalog"]["secret_fields_present"])
        self.assertLessEqual(len(encoded), 8192)
        for value in (secret_name, secret_value, hashlib.sha256(secret_value.encode()).hexdigest()):
            self.assertNotIn(value.encode(), encoded)

    def test_descriptor_walk_accepts_0755_but_rejects_symlink_and_metadata(self):
        self.fixture.write_config(managed())
        result = self.fixture.materialize(managed())
        self.assertTrue(result["managed_mapping_verified"])

        another = MappingFixture()
        self.addCleanup(another.close)
        real_home = another.home.parent / "real-home"
        real_home.mkdir()
        (real_home / "config.toml").write_bytes(managed())
        os.chmod(real_home / "config.toml", 0o600)
        another.home.rmdir()
        another.home.symlink_to(real_home, target_is_directory=True)
        with self.assertRaisesRegex(mapper.MappingError, "^descriptor_invalid$"):
            another.materialize(managed(), record=another.record())

        for mode in (0o644, 0o600):
            broken = MappingFixture()
            self.addCleanup(broken.close)
            broken.write_config(managed())
            if mode == 0o644:
                os.chmod(broken.config, mode)
            else:
                os.link(broken.config, broken.home / "second-link")
            with self.assertRaisesRegex(mapper.MappingError, "^config_metadata_invalid$"):
                mapper.materialize(
                    broken.record(), workspace_root=str(broken.workspace), expected_cwd=os.getcwd(),
                    expected_uid=broken.uid, base_policy_path=str(broken.base),
                    expected_base_sha256=hashlib.sha256(BASE_POLICY).hexdigest(),
                    output_dir=str(broken.output), mapping_policy_version="codex-mcp-map-v1")

        fifo = MappingFixture()
        self.addCleanup(fifo.close)
        os.mkfifo(fifo.config, 0o600)
        with self.assertRaisesRegex(mapper.MappingError, "^config_metadata_invalid$"):
            mapper.materialize(
                fifo.record(), workspace_root=str(fifo.workspace), expected_cwd=os.getcwd(),
                expected_uid=fifo.uid, base_policy_path=str(fifo.base),
                expected_base_sha256=hashlib.sha256(BASE_POLICY).hexdigest(),
                output_dir=str(fifo.output), mapping_policy_version="codex-mcp-map-v1")

    def test_descriptor_and_file_replacement_races_are_detected(self):
        self.fixture.write_config(managed())
        original_read = mapper._read_all

        def replace_after_read(fd):
            data = original_read(fd)
            replacement = self.fixture.home / "replacement.toml"
            replacement.write_bytes(managed("[mcp_servers.context7]"))
            os.chmod(replacement, 0o600)
            os.replace(replacement, self.fixture.config)
            return data

        with mock.patch.object(mapper, "_read_all", replace_after_read):
            with self.assertRaisesRegex(mapper.MappingError, "^descriptor_race$"):
                mapper.materialize(
                    self.fixture.record(), workspace_root=str(self.fixture.workspace),
                    expected_cwd=os.getcwd(), expected_uid=self.fixture.uid,
                    base_policy_path=str(self.fixture.base),
                    expected_base_sha256=hashlib.sha256(BASE_POLICY).hexdigest(),
                    output_dir=str(self.fixture.output), mapping_policy_version="codex-mcp-map-v1")
        self.assertEqual(list(self.fixture.output.iterdir()), [])

    def test_base_digest_existing_output_and_base_mcp_fail_without_overwrite(self):
        self.fixture.write_config(managed())
        with self.assertRaisesRegex(mapper.MappingError, "^base_policy_digest_mismatch$"):
            mapper.materialize(
                self.fixture.record(), workspace_root=str(self.fixture.workspace), expected_cwd=os.getcwd(),
                expected_uid=self.fixture.uid, base_policy_path=str(self.fixture.base),
                expected_base_sha256="0" * 64, output_dir=str(self.fixture.output),
                mapping_policy_version="codex-mcp-map-v1")

        self.fixture.base.write_bytes(BASE_POLICY + b"[mcp_servers.trace]\n")
        with self.assertRaisesRegex(mapper.MappingError, "^base_policy_invalid$"):
            mapper.materialize(
                self.fixture.record(), workspace_root=str(self.fixture.workspace), expected_cwd=os.getcwd(),
                expected_uid=self.fixture.uid, base_policy_path=str(self.fixture.base),
                expected_base_sha256=hashlib.sha256(self.fixture.base.read_bytes()).hexdigest(),
                output_dir=str(self.fixture.output), mapping_policy_version="codex-mcp-map-v1")

        self.fixture.base.write_bytes(BASE_POLICY)
        target = self.fixture.output / "codex-config.toml"
        target.write_text("PRESERVE")
        os.chmod(target, 0o600)
        with self.assertRaisesRegex(mapper.MappingError, "^output_exists$"):
            self.fixture.materialize(managed())
        self.assertEqual(target.read_text(), "PRESERVE")

    def test_base_policy_semantic_mcp_forms_refuse_without_publication(self):
        variants = [
            b'[ "mcp_servers".unmanaged ]\ncommand = "SYNTHETIC_ONLY"\n',
            b'[ mcp_servers . unmanaged ]\ncommand = "SYNTHETIC_ONLY"\n',
            b'["mcp_servers" . "unmanaged"]\ncommand = "SYNTHETIC_ONLY"\n',
            b"[ 'mcp_servers' . unmanaged ]\ncommand = \"SYNTHETIC_ONLY\"\n",
            b'[[ "mcp_servers" . unmanaged ]]\ncommand = "SYNTHETIC_ONLY"\n',
            b'mcp_servers.unmanaged.command = "SYNTHETIC_ONLY"\n',
            b'"mcp_servers" . unmanaged . command = "SYNTHETIC_ONLY"\n',
        ]
        for base in variants:
            with self.subTest(base=base):
                fixture = MappingFixture()
                self.addCleanup(fixture.close)
                fixture.write_config(managed())
                fixture.base.write_bytes(base)
                with self.assertRaisesRegex(mapper.MappingError, "^base_policy_invalid$"):
                    mapper.materialize(
                        fixture.record(), workspace_root=str(fixture.workspace),
                        expected_cwd=os.getcwd(), expected_uid=fixture.uid,
                        base_policy_path=str(fixture.base),
                        expected_base_sha256=hashlib.sha256(base).hexdigest(),
                        output_dir=str(fixture.output), mapping_policy_version="codex-mcp-map-v1")
                self.assertEqual(list(fixture.output.iterdir()), [])

    def test_publication_rejects_replaced_temp_inode_and_preserves_foreign_entry(self):
        self.fixture.write_config(managed())
        real_link = mapper.os.link
        replaced = []

        def replace_before_link(source, destination, **kwargs):
            if Path(destination).name == "codex-config.toml":
                source_path = Path(source)
                if not source_path.is_absolute():
                    source_path = self.fixture.output / source_path
                original = source_path.read_bytes()
                substitute = self.fixture.output / "synthetic-substitute"
                substitute.write_bytes(original.replace(b"medium", b"high  "))
                os.chmod(substitute, 0o600)
                os.replace(substitute, source_path)
                replaced.append(source_path.name)
            return real_link(source, destination, **kwargs)

        with mock.patch.object(mapper.os, "link", replace_before_link):
            with self.assertRaisesRegex(mapper.MappingError, "^output_invalid$"):
                self.fixture.materialize(managed())

        self.assertEqual(len(replaced), 1)
        self.assertFalse((self.fixture.output / "codex-config.toml").exists())
        self.assertFalse((self.fixture.output / "codex-mcp-catalog.json").exists())
        remaining = list(self.fixture.output.iterdir())
        self.assertEqual(len(remaining), 1)
        self.assertEqual(remaining[0].name, replaced[0])
        self.assertIn(b'high  ', remaining[0].read_bytes())

    def test_final_reopen_rejects_foreign_regular_file_before_any_read(self):
        foreign = self.fixture.root / "synthetic-private-canary"
        foreign.write_bytes(b"PRIVATE_SYNTHETIC_CANARY_ONLY")
        os.chmod(foreign, 0o600)
        foreign_inode = foreign.stat().st_ino
        directory_fd, identity = mapper._open_output_directory(
            str(self.fixture.output), self.fixture.uid)
        real_open = mapper.os.open
        real_read = mapper.os.read
        foreign_read_bytes = []

        def replace_before_reopen(name, flags, *args, **kwargs):
            if name == "codex-config.toml" and kwargs.get("dir_fd") == directory_fd:
                os.replace(foreign, self.fixture.output / name)
            return real_open(name, flags, *args, **kwargs)

        def record_foreign_read(fd, size):
            value = real_read(fd, size)
            if os.fstat(fd).st_ino == foreign_inode:
                foreign_read_bytes.append(len(value))
            return value

        try:
            with mock.patch.object(mapper.os, "open", replace_before_reopen), \
                    mock.patch.object(mapper.os, "read", record_foreign_read):
                with self.assertRaisesRegex(mapper.MappingError, "^output_invalid$"):
                    mapper._write_atomic(
                        str(self.fixture.output), directory_fd, identity, "codex-config.toml",
                        BASE_POLICY, self.fixture.uid)
        finally:
            os.close(directory_fd)

        self.assertEqual(sum(foreign_read_bytes), 0)
        self.assertEqual((self.fixture.output / "codex-config.toml").read_bytes(),
                         b"PRIVATE_SYNTHETIC_CANARY_ONLY")

    def test_final_reopen_refuses_fifo_nonblocking_before_any_read(self):
        foreign = self.fixture.root / "synthetic-private-fifo"
        os.mkfifo(foreign, 0o600)
        foreign_inode = foreign.stat().st_ino
        directory_fd, identity = mapper._open_output_directory(
            str(self.fixture.output), self.fixture.uid)
        real_open = mapper.os.open
        real_read = mapper.os.read
        final_flags = []
        foreign_reads = []

        def replace_before_reopen(name, flags, *args, **kwargs):
            if name == "codex-config.toml" and kwargs.get("dir_fd") == directory_fd:
                os.replace(foreign, self.fixture.output / name)
                final_flags.append(flags)
                if not flags & os.O_NONBLOCK:
                    raise BlockingIOError("synthetic refusal instead of blocking")
            return real_open(name, flags, *args, **kwargs)

        def record_foreign_read(fd, size):
            value = real_read(fd, size)
            if os.fstat(fd).st_ino == foreign_inode:
                foreign_reads.append(len(value))
            return value

        try:
            with mock.patch.object(mapper.os, "open", replace_before_reopen), \
                    mock.patch.object(mapper.os, "read", record_foreign_read):
                with self.assertRaisesRegex(mapper.MappingError, "^output_invalid$"):
                    mapper._write_atomic(
                        str(self.fixture.output), directory_fd, identity, "codex-config.toml",
                        BASE_POLICY, self.fixture.uid)
        finally:
            os.close(directory_fd)

        self.assertEqual(len(final_flags), 1)
        self.assertTrue(final_flags[0] & os.O_NONBLOCK)
        self.assertEqual(sum(foreign_reads), 0)
        self.assertTrue(stat.S_ISFIFO((self.fixture.output / "codex-config.toml").lstat().st_mode))

    def test_public_errors_suppress_causes_and_validate_semantic_types(self):
        missing_home = self.fixture.workspace / "alte-9-abcdef012345" / "codex-home"
        with self.assertRaisesRegex(mapper.MappingError, "^descriptor_invalid$") as caught:
            mapper._read_validated_config(str(missing_home), str(self.fixture.workspace), self.fixture.uid)
        rendered = "".join(traceback.format_exception(
            type(caught.exception), caught.exception, caught.exception.__traceback__))
        self.assertNotIn(missing_home.parent.name, rendered)
        self.assertNotIn("FileNotFoundError", rendered)

        malformed = [
            managed("[mcp_servers.trace]", 'command = ["SYNTHETIC_ONLY"]', 'args = ["serve"]'),
            managed("[mcp_servers.playwright]", 'command = "npx"', 'args = [["SYNTHETIC_ONLY"]]'),
        ]
        for data in malformed:
            with self.subTest(data=data):
                plan = mapper.build_mapping(data, "codex-mcp-map-v1")
                self.assertEqual(plan["failure"], "unverified_managed_config")
                self.assertFalse(plan["catalog"]["managed_mapping_verified"])

    def test_atomic_publication_removes_a_link_after_directory_fsync_failure(self):
        self.fixture.write_config(managed())
        real_fsync = mapper.os.fsync

        def fail_directory_fsync(fd):
            if stat.S_ISDIR(os.fstat(fd).st_mode):
                raise OSError("synthetic directory fsync failure")
            return real_fsync(fd)

        with mock.patch.object(mapper.os, "fsync", fail_directory_fsync):
            with self.assertRaisesRegex(mapper.MappingError, "^output_invalid$"):
                mapper.materialize(
                    self.fixture.record(), workspace_root=str(self.fixture.workspace),
                    expected_cwd=os.getcwd(), expected_uid=self.fixture.uid,
                    base_policy_path=str(self.fixture.base),
                    expected_base_sha256=hashlib.sha256(BASE_POLICY).hexdigest(),
                    output_dir=str(self.fixture.output), mapping_policy_version="codex-mcp-map-v1")
        self.assertEqual(list(self.fixture.output.iterdir()), [])

    def test_auth_and_agents_are_never_opened_or_changed(self):
        agents = self.fixture.home / "AGENTS.md"
        auth = self.fixture.home / "auth.json"
        agents.write_text("AGENTS_CONTEXT_CANARY\n")
        auth.write_text("AUTH_SECRET_CANARY\n")
        os.chmod(agents, 0o644)
        os.chmod(auth, 0o600)
        before = {path.name: (path.read_bytes(), path.stat().st_mode) for path in (agents, auth)}
        opened = []
        real_open = mapper.os.open

        def recording_open(path, *args, **kwargs):
            opened.append(os.fspath(path))
            return real_open(path, *args, **kwargs)

        with mock.patch.object(mapper.os, "open", recording_open):
            self.fixture.materialize(managed())
        self.assertNotIn("auth.json", opened)
        self.assertNotIn("AGENTS.md", opened)
        after = {path.name: (path.read_bytes(), path.stat().st_mode) for path in (agents, auth)}
        self.assertEqual(after, before)
        combined = b"".join(path.read_bytes() for path in self.fixture.output.iterdir())
        self.assertNotIn(b"AUTH_SECRET_CANARY", combined)
        self.assertNotIn(b"AGENTS_CONTEXT_CANARY", combined)
        self.assertNotIn(b"developerInstructions", combined)


if __name__ == "__main__":
    unittest.main(verbosity=2)
