query GetNavigation {
  sections(
    pagination: { page: 1, limit: 100 }
    sort: { field: "order", direction: ASC }
    filters: { base: {}, status: [active] }
  ) {
    sections {
      id
      name
      slug
      order
    }
  }
  popularTags: tags(
    pagination: { page: 1, limit: 10 }
    sort: { field: "createdAt", direction: DESC }
    filters: { base: {}, hasArticles: true }
  ) {
    tags {
      name
      slug
    }
  }
}

query GetUserMenu {
  me {
    id
    name
    handle
    photoUrl
    role
  }
}
