query GetArticle($slug: String!) {
  article(slug: $slug) {
    id
    title
    slug
    dek
    body
    excerpt
    featuredImage
    status
    publishedAt
    createdAt
    updatedAt
    author {
      id
      name
      slug: handle
      bio
      photoUrl
      socialLinks
    }
    section {
      name
      slug
    }
    tags {
      name
      slug
    }
  }
}

query GetGoneArticle($locale: Locale!, $sectionSlug: String!, $slug: String!) {
  gone(locale: $locale, sectionSlug: $sectionSlug, slug: $slug) {
    title
    firstPublishedAt
    unpublishedAt
    author {
      name
      handle
    }
    section {
      name
      slug
    }
  }
}
