query GetArticle($locale: Locale!, $sectionSlug: String!, $slug: String!, $preview: String) {
  article(locale: $locale, sectionSlug: $sectionSlug, slug: $slug, preview: $preview) {
    id
    translationId
    locale
    title
    slug
    dek
    body
    excerpt
    featuredImage
    cover {
      variants
      alt
    }
    bodyAssets {
      id
      alt
      caption
      attribution
      variants
      width
      height
    }
    status
    preview
    reeditUntil
    publishedAt
    firstPublishedAt
    createdAt
    updatedAt
    readingTime
    isTranslation
    sibling {
      locale
      path
    }
    author {
      id
      name
      slug: handle
      bio
      photoUrl
      socialLinks
    }
    section {
      name
      slug
    }
    format {
      name
      slug
    }
    tags {
      name
      slug
    }
  }
}

query GetGoneArticle($locale: Locale!, $sectionSlug: String!, $slug: String!) {
  gone(locale: $locale, sectionSlug: $sectionSlug, slug: $slug) {
    title
    firstPublishedAt
    unpublishedAt
    author {
      name
      handle
    }
    section {
      name
      slug
    }
  }
}
